FROM public.ecr.aws/aws-cli/aws-cli:2.13.36
WORKDIR /usr/local/bin
RUN curl -O https://rolesanywhere.amazonaws.com/releases/1.1.1/X86_64/Linux/aws_signing_helper
RUN chmod a+x aws_signing_helper
USER 1000
